Deductive reasoning is concluding something based on facts that have already been proved. For instance, I know that all dogs are mammals. My pet is a dog. Therefore, my pet must be a mammal. 

Inductive reasoning is concluding something based off of an observation. For instance, if all of the swans I have ever seen are white, I might recognize that pattern and assume that every swan in the world is white.

In [76]:
import pandas as pd

adult_df = pd.read_csv('adult.data')
adult_df.head()

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [77]:
adult_df.columns = ['age','workclass','fnlwgt','education','eduction_num','marital_status','occupation','relationship','race','sex','capital_gain','capital_loss','hours_per_week','native_country','income']

In [78]:
adult_df.head()

,age,workclass,fnlwgt,education,eduction_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [79]:
adult_df.dropna()
adult_df.drop_duplicates()

,age,workclass,fnlwgt,education,eduction_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32555,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32556,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32557,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32558,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32559,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [80]:
workclass_map = {'Private':0, 'Self-emp-not-inc':1, 'Self-emp-inc':2, 'Federal-gov':3, 
                 'Local-gov':4, 'State-gov':5, 'Without-pay':6, 'Never-worked':7}
adult_df['workclass'] = adult_df['workclass'].map(workclass_map)

education_map = {'Bachelors':0, 'Some-college':1, '11th':2, 'HS-grad':3, 'Prof-school':4, 
                 'Assoc-acdm':5, 'Assoc-voc':6, '9th':7, '7th-8th':8, '12th':9, 'Masters':10, 
                 '1st-4th':11, '10th':12, 'Doctorate':13, '5th-6th':14, 'Preschool':15}
adult_df['education'] = adult_df['education'].map(education_map)

marriage_map = {'Married-civ-spouse':0, 'Divorced':1, 'Never-married':2, 
                'Separated':3, 'Widowed':4, 'Married-spouse-absent':5, 'Married-AF-spouse':6}
adult_df['marital_status'] = adult_df['marital_status'].map(marriage_map)

occupation_map = {'Tech-support':0, 'Craft-repair':1, 'Other-service':2, 'Sales':3, 
                  'Exec-managerial':4, 'Prof-specialty':5, 'Handlers-cleaners':6, 
                  'Machine-op-inspct':7, 'Adm-clerical':8, 'Farming-fishing':9, 
                  'Transport-moving':10, 'Priv-house-serv':11, 
                  'Protective-serv':12, 'Armed-Forces':13}
adult_df['occupation'] = adult_df['occupation'].map(occupation_map)

relationship_map = {'Wife':0, 'Own-child':1, 'Husband':2, 'Not-in-family':3, 
                    'Other-relative':4, 'Unmarried':5}
adult_df['relationship'] = adult_df['relationship'].map(relationship_map)

race_map = {'White':0, 'Asian-Pac-Islander':1, 'Amer-Indian-Eskimo':2, 'Other':3, 'Black':4}
adult_df['race'] = adult_df['race'].map(race_map)

sex_map = {'Male':0, 'Female':1}
adult_df['sex'] = adult_df['sex'].map(sex_map)

country_map = {'United-States':0, 'Cambodia':1, 'England':2, 'Puerto-Rico':3, 
               'Canada':4, 'Germany':5, 'Outlying-US(Guam-USVI-etc)':6, 
               'India':7, 'Japan':8, 'Greece':9, 'South':10, 'China':11, 
               'Cuba':12, 'Iran':13, 'Honduras':14, 'Philippines':15, 
               'Italy':16, 'Poland':17, 'Jamaica':18, 'Vietnam':19, 
               'Mexico':20, 'Portugal':21, 'Ireland':22, 'France':23, 
               'Dominican-Republic':24, 'Laos':25, 'Ecuador':26, 'Taiwan':27, 
               'Haiti':28, 'Columbia':29, 'Hungary':30, 'Guatemala':31, 
               'Nicaragua':32, 'Scotland':33, 'Thailand':34, 'Yugoslavia':35, 
               'El-Salvador':36, 'Trinadad&Tobago':37, 'Peru':38, 'Hong':39, 
               'Holand-Netherlands':40}
adult_df['native_country'] = adult_df['native_country'].map(country_map)

income_map = {'<=50K ':0, '>50K ':1}
adult_df['income'] = adult_df['income'].map(income_map)

In [81]:
adult_df.head()

,age,workclass,fnlwgt,education,eduction_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,50,NaN,83311,NaN,13,NaN,NaN,NaN,NaN,NaN,0,0,13,NaN,NaN
1,38,NaN,215646,NaN,9,NaN,NaN,NaN,NaN,NaN,0,0,40,NaN,NaN
2,53,NaN,234721,NaN,7,NaN,NaN,NaN,NaN,NaN,0,0,40,NaN,NaN
3,28,NaN,338409,NaN,13,NaN,NaN,NaN,NaN,NaN,0,0,40,NaN,NaN
4,37,NaN,284582,NaN,14,NaN,NaN,NaN,NaN,NaN,0,0,40,NaN,NaN

I'm not sure why everything turned null when i changed it to numeric. 
I've done the exact same process on a different dataset and it has worked, 
so I don't know what the issue is. I went ahead and typed what the rest 
of the code would be had this part worked correctly.

In [82]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X = adult_df.drop('income', axis=1)
y = adult_df['income']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, 
                                                    random_state=50, stratify=y)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

ValueError: Input y contains NaN.

In [ ]:
adult_df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'eduction_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income'],
      dtype='str')

## DECISION TREE

In [ ]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt

features = ['age', 'workclass', 'fnlwgt', 'education', 'eduction_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country']

X = adult_df[features]
y = adult_df['income']

dtree = DecisionTreeClassifier()
dtree = dtree.fit(X, y)

tree.plot_tree(dtree, feature_names=features)

ValueError: Input y contains NaN.

### Tuning: 
I chose income as my y because I think it connects to all of the rest of the columns the most strongly. I think that each of the other columns would be a large factor in determining how much money someone makes. There were not really any other categories that I thought could have that kind of connection/correlation with the rest of the categories, so I wanted to see that relationship with income.

## RANDOM FOREST

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=400, random_state=50)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)
rf_tree = rf.estimators_[4]
tree.plot_tree(rf_tree)
plt.savefig("rf_tree.svg")

ValueError: could not convert string to float: ' State-gov'

## Tuning: 
There are over 32000 rows in this dataset. Becuase of this, I upped the number of estimators from 100 to 400 as to capture more of the dataset in the model. I am a bit concerned about overfitting here, though. It's hard to tell what the outcome would actually be since the code isn't working, but I'd be interested in the precision and recall of this model and if this actually would lead to an overfitting model.

## XGBOOST

In [ ]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train, y_train)

y_pred = xgb.predict(X_test)
y_pred

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1], got [' <=50K' ' >50K']

In [ ]:
from sklearn.metrics import ConfusionMatrixDisplay
ConfusionMatrixDisplay.from_estimator(xgb, X_test, y_test)

NotFittedError: need to call fit or load_model beforehand

## Tuning:
I think I would need to be able to see the confusion matrix to know how to tune this model.